config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  #商品一覧ページ
  root "products#index"

  #商品関連情報
  resources :products do
    member do
      get :buy              #商品購入
      patch :purchase       #payjp
      get :complete         #購入完了
    end
    collection do
      get 'category_children',defaults: { format: 'json' }             #子カテゴリー選択
      get 'category_grandchildren',defaults: { format: 'json' }        #孫カテゴリー選択
    end
  end

  #ユーザー関連情報
  resources :users, only: [:show] do
    member do
      get :login            #ログイン
      get :logout           #ログアウト
      get :profile          #プロフィール
      get :payment          #支払い方法
      get :credit           #クレジットカード情報入力
      get :identification   #本人情報
    end
  end
  
  #ユーザー新規登録
  resources :signup do
    collection do
      get 'step1'           #会員情報入力
      get 'step2'           #電話番号の確認
      get 'step2_5'         #電話番号認証
      get 'step3'           #発送元・お届け先住所入力
      get 'done'            #登録完了後のページ
    end
  end

  #クレジットカード登録 *payjp*
  resources :cards, only: [:new,:create]

end

app/views/shared/_breadcrumbs.html.haml
.breadcrumbs
  = breadcrumbs pretext: "",separator: " &rsaquo; ", class: "breadcrumbs-list"

app/views/shared/_footer.html.haml
.o-exhibit
  -if user_signed_in?
    = link_to new_product_path do
      .o-exhibit__image
        .o-exhibit__text
          出品
        .o-exhibit__icon
          = fa_icon 'camera', class: 'o-cameraicon', type:'submit'
  -else 
    = link_to new_user_session_path do
      .o-exhibit__image
        .o-exhibit__text
          出品
        .o-exhibit__icon
          = fa_icon 'camera', class: 'o-cameraicon', type:'submit'
          
.o-banner
  = image_tag '/images/footer.jpg', class: "o-footer-photo"
.o-footer
  .o-footer__menu
    .o-footer__main
      %h2.o-footer__main__title
        メルカリについて
      %ul.o-footer__main__lists
        %li.o-footer__main__list
          会社概要（運営会社）
        %li.o-footer__main__list
          採用情報
        %li.o-footer__main__list
          プレスリリース
        %li.o-footer__main__list
          公式ブログ
        %li.o-footer__main__list
          メルカリロゴ利用ガイドライン
        %li.o-footer__main__icon
          = fa_icon 'twitter', class: 'footericon'
          = fa_icon 'facebook-square', class: 'footericon'

    .o-footer__main
      %h2.o-footer__main__title
        ヘルプ&ガイド
      %ul.o-footer__main__lists
        %li.o-footer__main__list
          メルカリガイド
        %li.o-footer__main__list
          らくらくメルカリ便
        %li.o-footer__main__list
          ゆうゆうメルカリ便
        %li.o-footer__main__list
          大型メルカリ便
        %li.o-footer__main__list
          車体取引ガイド
        %li.o-footer__main__list
          メルカリあんしん・あんぜん宣言！
        %li.o-footer__main__list
          偽ブランド品撲滅への取り組み
        %li.o-footer__main__list
          メルカリボックス

    .o-footer__main
      %h2.o-footer__main__title
        プライバシーと利用規約
      %ul.o-footer__main__policys
        %li.o-footer__main__list
          プライバシーポリシー
        %li.o-footer__main__list
          メルカリ利用規約
        %li.o-footer__main__list
          あんしんスマホサポート制度に関する利用特約
        %li.o-footer__main__list
          コンプライアンスポリシー
          
      %ul.o-footer__main__lists
        %li.o-footer__main__list
          個人データの安全管理に係る基本方針
        %li.o-footer__main__list
          特定商取引に関する表記
        %li.o-footer__main__list
          資産決済法に基づく表示
        %li.o-footer__main__list
          法令順守と犯罪防止のために
    
    .o-footer__main
      %h2.o-footer__main__title
        国
      %ul.o-footer__main__lists
        %li.o-footer__main__list
          日本
        %li.o-footer__main__list
          United States
        
  .o-footer__bottom
    .o-footer__bottom__image
      = image_tag '/images/fmarket_logo_red.svg',class: 'footerlog'
    .o-footer__bottom__text
      @ 2019 Fmarket

app/views/shared/_header.html.haml
.k-header
  .k-top
    .k-top__logo-and-search
      .k-top__logo-and-search__logo
        = link_to "/" do
          = image_tag '/images/fmarket_logo_red.svg', height: '', width: '', class: 'k-top__logo-and-search__logo__img'
      .k-form
        %form.k-form
          %input.k-input{placeholder:'何かお探しですか？'}
          .btn
            %label{class: "form__mask"}
              = fa_icon 'search', class: 'icon', type:'submit', fa_icon: 'search'
    .k-top__list
      .k-top__list__menu
        .k-top__list__menu__link
          %i.k-fa
            =image_tag "/images/menu.svg",width: '20',heigth: '16',class: 'k-faicon'
            カテゴリーから探す
        .k-top__list__menu__link
          %i.fa.fa-tag
          ブランドから探す
      .k-top__list__list
        - if user_signed_in?
          .k-user-signed
            = link_to "/" do
              .fa.k-user-signed__i.fa-heart-o
              %span.k-user-signed__text いいね!一覧
            = link_to "/" do
              .fa.k-user-signed__i.fa-bell-o
              %span.k-user-signed__text お知らせ
            = link_to "/" do
              .fa.k-user-signed__i.fa-check
              %span.k-user-signed__text やることリスト
            = link_to user_path(current_user.id), class: "" do
              = image_tag '/images/member.png', height: '', width: '', class: 'k-user-signed__img'
              %span.k-user-signed__text 
                マイページ
        - else
          = link_to signup_index_path  ,class: 'signupbtn' do
            .k-top__list__list__signup 
              新規会員登録
          &nbsp;&nbsp;
          = link_to new_user_session_path, class: "signupbtn" do
            .k-top__list__list__login 
              ログイン