config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  #商品一覧ページ
  root "products#index"

  #商品関連情報
  resources :products do
    member do
      get :buy              #商品購入
      patch :purchase       #payjp
      get :complete         #購入完了
    end
    collection do
      get 'category_children',defaults: { format: 'json' }             #子カテゴリー選択
      get 'category_grandchildren',defaults: { format: 'json' }        #孫カテゴリー選択
    end
  end

  #ユーザー関連情報
  resources :users, only: [:show] do
    member do
      get :login            #ログイン
      get :logout           #ログアウト
      get :profile          #プロフィール
      get :payment          #支払い方法
      get :credit           #クレジットカード情報入力
      get :identification   #本人情報
    end
  end
  
  #ユーザー新規登録
  resources :signup do
    collection do
      get 'step1'           #会員情報入力
      get 'step2'           #電話番号の確認
      get 'step2_5'         #電話番号認証
      get 'step3'           #発送元・お届け先住所入力
      get 'done'            #登録完了後のページ
    end
  end

  #クレジットカード登録 *payjp*
  resources :cards, only: [:new,:create]

end

app/controllers/cards_controller.rb
class CardsController < ApplicationController

  require "payjp"
  before_action :set_card

  # カードの登録画面。送信ボタンを押すとcreateアクションへ ----------------
  def new
    creditcard = CreditCard.where(user_id: current_user.id).first
    redirect_to "/cards/new" if creditcard.present?
  end


  # PayjpとCardのデータベースを作成 --------------------------------
  def create
    Payjp.api_key = 'sk_test_96c344952e792691d9fc840e'    #Pay.jpの秘密鍵

    if params['payjp-token'].blank?
      redirect_to action: "new"
    else
      # トークンが正常に発行されていたら、顧客情報をPAY.JPに登録します。
      customer = Payjp::Customer.create(
        description: current_user.family_name + current_user.first_name,  #PAY.JPの顧客情報に表示する名前
        email: current_user.email,                                        #PAY.JPの顧客情報に表示するemail
        card: params['payjp-token'],                                      # 直前のnewアクションで発行され、送られてくるトークンをここで顧客に紐付けて永久保存
        metadata: {user_id: current_user.id}                              # 無くてもOK。
      )
      @creditcard = CreditCard.new(user_id: current_user.id, customer_id: customer.id, card_id: customer.default_card)
      if @creditcard.save
        redirect_to "/signup/done"
      else
        redirect_to action: "create"
      end
    end
  end

  private

  # ログインユーザーのクレジット情報
  #（顧客id と カードID)を取得 --------------------------------------
  def set_card
    @creditcard = CreditCard.where(user_id: current_user.id).first if CreditCard.where(user_id: current_user.id).present?
  end
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/views/cards/new.html.haml
.h-user-body
  = render "signup/signup-header"
  .h-user-main
    .h-user-contents
      %h2.h-user-title
        支払い方法
      .h-user-content
        = form_tag(cards_path, method: :post, class: 'h-user-form', name: "inputForm") do
          .h-user-form-box

            .h-form-group
              %label.h-label
                カード番号
              %span.h-form-require
                必須
              %input.h-input-default{maxlength: "16", name: "card_number", placeholder: "半角数字のみ", type: "text", id: "card_number"}/
              .h-singnup-card-list
                = image_tag  "/images/cards.png", height: 21

            .h-form-group
              %label.h-label{for: "expiration_date"}
                有効期限
              %span.h-form-require
                必須
              %br
              .h-birthday-select-wrap
                .h-select-wrap-card
                  %i.h-icon-arrow-bottom
                  %select.h-select-default{maxlength: "2", name: "exp_month", type: "text", id: "exp_month"}
                    %option{value: "1"}01
                    %option{value: "2"}02
                    %option{value: "3"}03
                    %option{value: "4"}04
                    %option{value: "5"}05
                    %option{value: "6"}06
                    %option{value: "7"}07
                    %option{value: "8"}08
                    %option{value: "9"}09
                    %option{value: "10"}10
                    %option{value: "11"}11
                    %option{value: "12"}12
                %span 月

              .h-birthday-select-wrap
                .h-select-wrap-card
                  %i.h-icon-arrow-bottom
                  %select.h-select-default{maxlength: "4", name: "exp_year", type: "text", id: "exp_year"}
                    %option{value: "2019"}19
                    %option{value: "2020"}20
                    %option{value: "2021"}21
                    %option{value: "2022"}22
                    %option{value: "2023"}23
                    %option{value: "2024"}24
                    %option{value: "2025"}25
                    %option{value: "2026"}26
                    %option{value: "2027"}27
                    %option{value: "2028"}28
                    %option{value: "2029"}29
                %span 年

            .h-form-group
              %label.h-label{for: "security_code"}
                セキュリティーコード
              %span.h-form-require
                必須
              %input.h-input-default{maxlength: "3", name: "cvc", placeholder: 'カード背面4桁もしくは3桁の番号', type: "text", id: "cvc"}
            
            .h-text-right
              %p
                = link_to root_path, class: "h-text-link" do
                  カード裏面の番号とは？
            .content-bottom#card_token
              %input.h-btn-default.h-btn-red{type: "submit", id: "token_submit", value: "次へ進む"} 


  = render "signup/signup-footer"

-# プログレスバー用 css 記述↓------------------------------------------------------------------------------------------------------------------------
:css
  #through .progress-status_bar{
      background: #ea352d;
  }  
  #active .progress-status{
      background: #ea352d;
  }
  #active .progress-status_bar{
      background: #ea352d;
  }
  #address .progress-status{
      background: #ea352d;
  }
  #address .progress-status_bar{
      background: #ea352d;
  }
  #payment{
    color: #ea352d;
  }
  #payment .progress-status{
      background: #ea352d;
  }

-# ↓↓↓ submitボタンを押された時にトークンを作成する処理-----------------------------------------------------------------------------------------------------

:javascript
  document.addEventListener(
  "DOMContentLoaded", (e) => {
    Payjp.setPublicKey("pk_test_2489a8be63710a3ea5c21172");    //Pay.jpの公開鍵
    const btn = document.getElementById('token_submit');       //IDがtoken_submitの場合に取得されます
    btn.addEventListener("click", (e) => {                     //ボタンが押されたときに作動します
      e.preventDefault();                                      //ボタンを一旦無効化します

      //カード情報生成
      const card = {
        number: document.getElementById("card_number").value,
        cvc: document.getElementById("cvc").value,
        exp_month: document.getElementById("exp_month").value,
        exp_year: document.getElementById("exp_year").value
      }; //入力されたデータを取得します。

      //トークン生成
      Payjp.createToken(card, (status, response) => {
        if (status === 200) { //成功した場合
          $("#card_number").removeAttr("name");
          $("#cvc").removeAttr("name");
          $("#exp_month").removeAttr("name");
          $("#exp_year").removeAttr("name"); //カード情報を自分のサーバにpostせず削除します
          $("#card_token").append(
            $('<input type="hidden" name="payjp-token">').val(response.id)
          ); //トークンを送信できるように隠しタグを生成
          document.inputForm.submit();
          alert("登録が完了しました"); //確認用
        } else {
          alert("カード情報が正しくありません。"); //確認用
        }
      });
    });
  },false);