config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  #商品一覧ページ
  root "products#index"

  #商品関連情報
  resources :products do
    member do
      get :buy              #商品購入
      patch :purchase       #payjp
      get :complete         #購入完了
    end
    collection do
      get 'category_children',defaults: { format: 'json' }             #子カテゴリー選択
      get 'category_grandchildren',defaults: { format: 'json' }        #孫カテゴリー選択
    end
  end

  #ユーザー関連情報
  resources :users, only: [:show] do
    member do
      get :login            #ログイン
      get :logout           #ログアウト
      get :profile          #プロフィール
      get :payment          #支払い方法
      get :credit           #クレジットカード情報入力
      get :identification   #本人情報
    end
  end
  
  #ユーザー新規登録
  resources :signup do
    collection do
      get 'step1'           #会員情報入力
      get 'step2'           #電話番号の確認
      get 'step2_5'         #電話番号認証
      get 'step3'           #発送元・お届け先住所入力
      get 'done'            #登録完了後のページ
    end
  end

  #クレジットカード登録 *payjp*
  resources :cards, only: [:new,:create]

end

app/models/product.rb
class Product < ApplicationRecord

  # validation
  validates :name,                 presence: true, length: {maximum: 40}
  validates :description,          presence: true, length: {maximum: 40}
  validates :condition,            presence: true
  validates :shipping_charge,      presence: true
  validates :shipping_area,        presence: true
  validates :shipping_date,        presence: true
  validates :shipping_method,      presence: true
  validates :category_id,          presence: true
  validates :seller_id,            presence: true
  validates :price,                presence: true, numericality: { only_integer: true, greater_than: 299, less_than: 9999999}

  # associate
  belongs_to                    :user
  belongs_to                    :category
  belongs_to                    :size,        optional: true
  belongs_to                    :brand,       optional: true
  has_many                      :images,      dependent: :destroy
  accepts_nested_attributes_for :images,      allow_destroy: true
  belongs_to :seller, class_name: "User"
  belongs_to :buyer, class_name: "User"


  enum condition:[:"",:"新品、未使用",:"未使用に近い",:"目立った傷や汚れなし",:"やや傷や汚れあり",:"傷や汚れあり",:"全体的に状態が悪い"], _prefix: true

  enum shipping_charge: [:"",:"送料込み(出品者負担)",:"着払い(購入者負担)"] , _prefix: true
  enum shipping_area: [:"",:"北海道",:"青森県",:"岩手県",:"宮城県",:"秋田県",:"山形県",:"福島県",
  :"茨城県",:"栃木県",:"群馬県",:"埼玉県",:"千葉県",:"東京都",:"神奈川県",
  :"新潟県",:"富山県",:"石川県",:"福井県",:"山梨県",:"長野県",:"岐阜県",:"静岡県",:"愛知県",:"三重県",:"滋賀県",:"京都府",:"大阪府",:"兵庫県",:"奈良県",:"和歌山県", :"鳥取県",:"島根県",:"岡山県",:"広島県",:"山口県",:"徳島県",:"香川県",:"愛媛県",:"高知県",:"福岡県",:"佐賀県",:"長崎県",:"熊本県",:"大分県",:"宮崎県",:"鹿児島県",:"沖縄県"  ] , _prefix: true
  enum shipping_date:[:"",:"1~2日で発送", :"2~3日で発送",:"4~7日で発送"], _prefix: true

  enum shipping_method:[:"",:"未定",:"らくらくメルカリ便",:"ゆうメール",:"レターパック",:"普通郵便(定形、定形外)",:"クロネコヤマト",:"ゆうパック",:"クリックポスト",:"ゆうパケット"], _prefix: true


  def next
    Product.where("id < ?",id).order("id DESC").first
  end

  def previous
    Product.where("id > ?", id).order("id ASC").first
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_card, only:[:buy,:purchase]

  # 商品一覧 -----------------------------------
  def index
    @products = Product.order("created_at DESC")
  end

  # 商品出品 ------------------------------------
  def new
    @product = Product.new
    @product.images.build
  end

  # 子カテゴリー ----------------------------------
  def category_children
    @category_children = Category.find_by(name: "#{params[:parent_name]}", ancestry: nil).children
  end

  # 孫カテゴリー ----------------------------------
  def category_grandchildren
    @category_grandchildren = Category.find("#{params[:child_id]}").children
  end

  # 商品出品の保存 -------------------------------
  def create
    @product= Product.new(
      category_id: params[:category_id].to_i,
      name: product_params[:name],
      description: product_params[:description],
      condition: product_params[:condition],
      shipping_charge: product_params[:shipping_charge],
      shipping_area: product_params[:shipping_area],
      shipping_date: product_params[:shipping_date],
      shipping_method: product_params[:shipping_method],
      price: product_params[:price],
      seller_id: current_user.id
    )
    if @product.save
      params[:images][:image].each do |image|
        @product.images.create(image: image, product_id: @product.id)
      end
      redirect_to root_path
    else
      @product.images.build
      render action: 'new'
    end
  end

  # 出品商品の編集 -------------------------------
  def edit
    @product = Product.find(params[:id])
  end

  # 出品商品の更新 -------------------------------
  def update
    product = Product.find(params[:id])
    product.update(
      category_id: params[:category_id].to_i,
      name: product_params[:name],
      description: product_params[:description],
      condition: product_params[:condition],
      shipping_charge: product_params[:shipping_charge],
      shipping_area: product_params[:shipping_area],
      shipping_date: product_params[:shipping_date],
      shipping_method: product_params[:shipping_method],
      price: product_params[:price],
      seller_id: current_user.id
    )
    product.images.update(
      image: product_params[:images_attributes]["0"]["image"]
    )
    redirect_to root_path
  end

  # 商品詳細 ------------------------------------
  def show
    @images = Image.includes(:product).order('id desc')
    @product = Product.find(params[:id])
    @seller = User.find(@product.seller_id)
  end

  
  require 'payjp'

  # 商品の購入 ----------------------------------
  def buy
    @images = Image.includes(:product)
    @product = Product.find(params[:id])
    
    if @creditcard.blank?
      redirect_to controller: "cards", action: "new"                              #登録された情報がない場合にカード登録画面に移動
    else
      Payjp.api_key = "sk_test_96c344952e792691d9fc840e"
      customer = Payjp::Customer.retrieve(@creditcard.customer_id)                #保管した顧客IDでpayjpから情報取得
      @default_card_information = customer.cards.retrieve(@creditcard.card_id)    #カード情報表示のためインスタンス変数に代入
    end
  end

  # Pay.jp側に購入者情報を送信 ---------------------
  def purchase
    @product = Product.find(params[:id])
    @product.update(buyer_id: current_user.id)     #productテーブルにbuyer_idを入れる

    card_token = @creditcard.customer_id if @creditcard.present?
    Payjp.api_key = "sk_test_96c344952e792691d9fc840e"
    Payjp::Charge.create(
      amount: @product.price,
      customer: card_token,
      currency: 'jpy'
    )
    redirect_to action: 'complete'
  end

  # 購入完了画面 ---------------------------------
  def complete
  end
  
  # 商品の削除 -----------------------------------
  def destroy
    @product = Product.find(params[:id])
    if user_signed_in? && @product.seller_id == current_user.id
      @product.destroy
      redirect_to root_path
    else
      render acction: :show
    end
  end

  private

  # 入力された商品情報を取得 ------------------------
  def product_params
    params.require(:product).permit(
      :name, 
      :description,
      :condition, 
      :shipping_charge,
      :shipping_area,
      :shipping_date,
      :shipping_method,
      :category_id,
      :buyer_id,
      :size_id,
      :brand_id,
      :price,
      images_attributes: [:image,:product_id]).merge(seller_id: current_user.id)
  end

  # ログインユーザーのクレジット情報
  #（顧客id と カードID)を取得 -----------------------
  def set_card
    if user_signed_in?
      @creditcard = CreditCard.where(user_id: current_user.id).first if CreditCard.where(user_id: current_user.id).present?
    else
      @creditcard = 'nill'
    end
  end

end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_details.html.haml
.k-product-details
  .k-product-details__contents
    %h2.k-product-details__contents__title
      = @product.name
    -# 下記の説明は、ログインしていない場合のみ表示される文章
    %h2.k-product-details__contents__explanation
    - unless user_signed_in?
      『
      = @product.name
      』は、53回の取引実績を持つ
      = @seller.nickname
      さんから出品されました。
      = @product.shipping_area
      から
      = @product.shipping_date
      されます。
    .k-product-details__contents__content

      -if @product.buyer_id.present?
        .k-product-details__contents__content__left-sold
          %table.k-product-details__contents__content__left-sold__picture
            %tr
              %td{cellpadding: "0", align: "center"}
                = image_tag @product.images.last.image.url, height: '300', width: '300', alt: 'img1', class: 'k-product-details__contents__content__left-sold__picture__img'
                .k-product-details__contents__content__sold
                  .k-product-details__contents__content__sold__inner
                    SOLD
          .k-product-details__contents__content__left-sold__pictures
            -@images.each do |image|
              - if image.product_id == @product[:id]
                = image_tag image.image.url, class: 'k-product-details__contents__content__left-sold__pictures__imgs'

      -else
        .k-product-details__contents__content__left
          %table.k-product-details__contents__content__left__picture
            %tr
              %td{cellpadding: "0", align: "center"}
                = image_tag @product.images.last.image.url, height: '300', width: '300', alt: 'img2', class: 'k-product-details__contents__content__left__picture__img'
          .k-product-details__contents__content__left__pictures
            -@images.each do |image|
              - if image.product_id == @product[:id]
                = image_tag image.image.url, class: 'k-product-details__contents__content__left__pictures__imgs'


      .k-product-details__contents__content__right
        %table.k-table
          %tbody
            %tr
              %td{bgcolor: "#fafafa"} 出品者
              %td
                %p
                = link_to '' ,class: 'k-password-link-a' do
                  = @seller.nickname
                %p 
                .fa.fa-smile-o.k-face__pink
                ××
                .fa.fa-meh-o.k-face__yellow
                ×
                .fa.fa-frown-o.k-face__blue
                ×
            %tr
              %td{bgcolor: "#fafafa"}  カテゴリー
              %td
                %p

                = link_to '' ,class: 'k-password-link-a' do
                  = @product.category.root.name
                %p
                = link_to '' ,class: 'k-password-link-a' do
                  .fa.fa-angle-right
                  = @product.category.parent.name
                %p
                = link_to '' ,class: 'k-password-link-a' do
                  .fa.fa-angle-right
                  = @product.category.name

            %tr
              %td{bgcolor: "#fafafa"}  ブランド
              %td
                = link_to '' ,class: 'k-password-link-a' do
                  &nbsp;
            %tr
              %td{bgcolor: "#fafafa"}  商品の状態
              %td
                = @product.condition
            %tr
              %td{bgcolor: "#fafafa"}  配送料の負担
              %td
                = @product.shipping_charge
            %tr
              %td{bgcolor: "#fafafa"}  配送の方法
              %td
                = @product.shipping_method
            %tr
              %td{bgcolor: "#fafafa"}  配送元の地域
              %td
                = link_to '' ,class: 'k-password-link-a' do
                  = @product.shipping_area
            %tr
              %td{bgcolor: "#fafafa"}  発送日の目安
              %td
                = @product.shipping_date

    .k-product-details__contents__price-box
      %span.k-product-details__contents__price-box__price
        ¥
        = @product.price.to_s(:delimited)
        %span.k-product-details__contents__price-box__text
          (税込)
        %span.k-product-details__contents__price-box__shipping-fee
          送料込み
  
    -if @product.buyer_id.present?
      .k-product-details__contents__buy-not
        売り切れました
    -elsif user_signed_in? && current_user.id == @product.seller.id

    - else 
      -if user_signed_in?
        = link_to buy_product_path ,class: 'k-buy-a' do
          .k-product-details__contents__buy
            購入画面に進む
      - else
        = link_to new_user_session_path ,class: 'k-buy-a' do
          .k-product-details__contents__buy
            購入画面に進む

    .k-product-details__contents__details
      = @product['description']
    .k-product-details__contents__container
      .k-product-details__contents__container__left
        .k-circle
          = link_to '' ,class: 'k-black-a' do
            .k-product-details__contents__container__left__like
              .fa.k-product-details__item-box__main__products__items-box__item__price__love__i.fa-heart-o
              いいね!
        .k-circle
          = link_to '' ,class: 'k-black-a' do
            .k-product-details__contents__container__left__report
              %i.k-product-details__contents__container__left__report__i.fa.fa-flag-o
              %span.k-product-details__contents__container__left__report__text 不適切な商品の広告
      .k-product-details__contents__container__right
        = link_to '' ,class: 'k-blue-a' do
          .fa.fa-lock
          %span.k-product-details__contents__container__right__text
            = link_to '' ,class: 'k-relief' do
              あんしん・あんぜんへの取り組み
    - if user_signed_in? && @product.seller_id == current_user.id
      = link_to edit_product_path ,class: 'k-buy-a' do
        .k-product-details__contents__buy
          商品の編集
      = link_to "/products/#{@product.id}", class: "k-destoy", method: :delete do
        .k-product-details__contents__buy-not
          商品の削除

  .k-product-details__comment
    .k-product-details__comment__post
      .k-product-details__comment__post__form
        %p.k-product-details__comment__post__form__p 相手のことを考え丁寧なコメントを心がけましょう。不快な言葉遣いなどは利用制限や退会処分となることがあります。
        %textarea.k-product-details__comment__post__form__textarea{:name => "body", :type => "text", :value => ""}
        .k-product-details__comment__post__form__textarea__button
        %button.k-product-details__comment__post__form__button コメントする

  %ul.k-product-details__itemlink
    %li.k-product-details__itemlink__prev
      - if @product.previous.present?
        = link_to product_path(@product.previous.id), class: 'k-password-link-a' do
          .fa.fa-angle-left
          = @product.previous.name
    %li.k-product-details__itemlink__next
      - if @product.next.present?
        = link_to product_path(@product.next), class: 'k-password-link-a' do
          = @product.next.name
          .fa.fa-angle-right

  .k-product-details__supply
    .k-product-details__supply__margin
    %ul.k-product-details__supply__contents
      %li.k-product-details__supply__contents__box
        .k-product-details__supply__contents__box__facebook
          .fa.fa-facebook-official
        
      %li.k-product-details__supply__contents__box
        .k-product-details__supply__contents__box__twitter
          .fa.fa-twitter

      %li.k-product-details__supply__contents__box
        .k-product-details__supply__contents__box__pinterest
          .fa.fa-pinterest




  %nav.k-product-details__footer
    %ul.k-product-details__footer__ul
      %li
        = link_to '/' ,class: 'k-footer-root' do
          %span メルカリ
      %i.k-product-details__footer__i.fa.fa-angle-right
      %li
        %span.k-product-details__footer__title
          = @product.name

app/views/products/_product-error-messages.html.haml
- if product.errors.any?
  - unless product.valid?
    - if errors = product.errors.full_messages_for(column.to_sym)
      %ul
        - errors.each do |error|
          %li.product-error-messages-signup=error

:css
  .product-error-messages-signup{
    font-family: "Source Sans Pro", Helvetica, Arial, 游ゴシック体, YuGothic, メイリオ, Meiryo, sans-serif;
    color: #ea352d;
    margin-top: 8px;
  }

app/views/products/_product.html.haml
.o-main
  .slick-container
    %div
      = image_tag "main.jpg",class: "o-main-photo"
    %div
      = image_tag "main2.jpg",class: "o-main-photo"
    %div
      = image_tag "main3.jpg",class: "o-main-photo"
      
  .o-category
    %h2.o-category__title
      人気のカテゴリー
    .o-category__list
      %ul.o-category__list__total
        %li.o-category__list__details
          レディース
        %li.o-category__list__details
          メンズ
        %li.o-category__list__details
          家電・スマホ・カメラ

  .o-contents 
    .o-contents__content
      .o-contents__content-main
        .o-contents__text
          %h3.o-contents__name
            レディース新着アイテム
        .o-contents__menu
          -@products.each do |product|
            -if  (product.category_id < 200)
              = link_to product_path(product) do
                %ul.o-contents__menu__items
                  %li.o-contents__menu__item
                    %figure.o-contents__menu__box
                      =image_tag product.images.last.image.url,class: "o-contents__menu__image" 
                      -if product.buyer_id.present?
                        .o-contents__menu__sold
                          .o-contents__menu__sold__inner SOLD
                      .span.o-price
                        ¥
                        =product.price.to_s(:delimited)
                      %figcaption.o-contents__menu__texts
                        %span.o-contents__menu__text
                          =product.name

    .o-contents__content
      .o-contents__content-main
        .o-contents__text
          %h3.o-contents__name
            メンズ新着アイテム
        .o-contents__menu
          -@products.each do |product|
            -if (product.category_id >= 200 && product.category_id < 346)
              = link_to product_path(product) do
                %ul.o-contents__menu__items
                  %li.o-contents__menu__item
                    %figure.o-contents__menu__box
                      =image_tag product.images.last.image.url,class: "o-contents__menu__image" 
                      -if product.buyer_id.present?
                        .o-contents__menu__sold
                          .o-contents__menu__sold__inner SOLD
                      .span.o-price
                        ¥
                        =product.price.to_s(:delimited)
                      %figcaption.o-contents__menu__texts
                        %span.o-contents__menu__text
                          =product.name

    .o-contents__content
      .o-contents__content-main
        .o-contents__text
          %h3.o-contents__name
            家電・スマホ・カメラ新着アイテム
        .o-contents__menu
          -@products.each do |product|
            -if (product.category_id >= 898 && product.category_id < 984)
              = link_to product_path(product) do
                %ul.o-contents__menu__items
                  %li.o-contents__menu__item
                    %figure.o-contents__menu__box
                      =image_tag product.images.last.image.url,class: "o-contents__menu__image" 
                      -if product.buyer_id.present?
                        .o-contents__menu__sold
                          .o-contents__menu__sold__inner SOLD
                      .span.o-price
                        ¥
                        =product.price.to_s(:delimited)
                      %figcaption.o-contents__menu__texts
                        %span.o-contents__menu__text
                          =product.name

    .o-contents__content
      .o-contents__content-main
        .o-contents__text
          %h3.o-contents__name
            その他新着アイテム
        .o-contents__menu
          -@products.each do |product|
            -if (product.category_id >= 346 && product.category_id < 898) || (product.category_id >= 984) 
              = link_to product_path(product) do
                %ul.o-contents__menu__items
                  %li.o-contents__menu__item
                    %figure.o-contents__menu__box
                      =image_tag product.images.last.image.url,class: "o-contents__menu__image" 
                      -if product.buyer_id.present?
                        .o-contents__menu__sold
                          .o-contents__menu__sold__inner SOLD
                      .span.o-price
                        ¥
                        =product.price.to_s(:delimited)
                      %figcaption.o-contents__menu__texts
                        %span.o-contents__menu__text
                          =product.name

app/views/products/buy.html.haml
.o-buycontainer
  %header.o-proexhibit__header
    %h2.o-proexhibit__headerimage
      = link_to root_path do
        = image_tag( '/images/fmarket_logo_red.svg',  class: 'o-proexhibit__headerimg' )
  .o-buymain
    %section.o-buysection
      %h2.o-buytitle 購入内容の確認
      %section.o-buycontents
        .o-buycontent
          %h3.o-buycontent
            = image_tag @product.images.last.image.url,class: "o-buycontent__image" 
          %p.o-buycontent__name
            = @product.name
        .o-buyform
          %p.o-buyform__sabprice
            ¥
            = @product.price.to_s(:delimited)
            %span.o-buyform__sabfee 送料込み
        %ul.o-buypoints
          %li.o-pointtext 
            ポイントはありません
        %ul.o-buyprices
          %li.o-buyprice
            %p
              支払い金額
              %span.o-buyprice__cell
                ¥
                = @product.price.to_s(:delimited)
        .o-payjp-btn
          = form_for(@product,url: purchase_product_path) do
            %button.o-buyprice__btn 購入する
            
      %section.o-buyusers
        .o-buyuser
          %h3.o-buyuser__title 配送先
          %address.o-buyuser__text
            〒
            = current_user.address.postal_code.to_s(:phone)
            %br
              = current_user.address.prefecture.name + current_user.address.municipalities + current_user.address.house_number
            %br
              = current_user.family_name + current_user.first_name 

      %section.o-buyusers
        .o-buyuser
          %h3.o-buyuser__title 支払い方法
          .o-buyuser__text
            クレジットカード
            .content__credit-cards__list--pay-num
              = "**** **** ****" + @default_card_information.last4
              - exp_month = @default_card_information.exp_month.to_s
              - exp_year = @default_card_information.exp_year.to_s.slice(2,3)
              = exp_month + " / " + exp_year

  = render "signup/signup-footer"
          

app/views/products/complete.html.haml
.o-buycontainer
  %header.o-proexhibit__header
    %h2.o-proexhibit__headerimage
      = link_to root_path do
        = image_tag( '/images/fmarket_logo_red.svg',  class: 'o-proexhibit__headerimg' )
  
  .o-buymain
    %section.o-buycomplete
      %section.o-buycontents
        .o-buyformm
          %span.o-buyformm__sabfee
            購入が完了しました
          = link_to root_path,class:"o-complete-root" do
            .o-proexhibit__linkgray
              トップページに戻る

  = render "signup/signup-footer"

app/views/products/edit.html.haml
= form_for @product do |f|
  %header.o-proexhibit__header
    %h2.o-proexhibit__headerimage
      = link_to root_path do
        = image_tag( '/images/fmarket_logo_red.svg',  class: 'o-proexhibit__headerimg' )

  .o-proexhibit__main
    %section.o-proexhibit__inner
      .o-proexhibit__title
        %h2.o-proexhibit__titlename
          商品の情報を入力
      .o-proexhibit__inner__form
        .o-proexhibit__imageuploads
          = f.label '出品画像', class: 'o-proexhibit__imageuploads__title'
          %span.o-proexhibit__required 必須
          %p.o-proexhibit__imageuploads__text
            最大10枚までアップロードできます
            
        = f.fields_for :images do |i|
          .k-edit-imgup
            .o-edit-image-move
              .o-edit-image-move__image
                = image_tag i.object.image.url, class: 'o-edit-image-move__image__img'
              .o-edit-image-move__up
                .o-edit-image-move__up__edit 編集
                .o-edit-image-move__up__choice 削除
            =i.label :image do
              .o-edit-proexhibit__imageuploads__file
                = i.file_field :image,class: "o-proexhibit__imageuploads__fileimage, o-hidden"
                %pre.o-proexhibit__imageuploads__filetext
                  ドラックアンドドロップ
                  またはクリックしてファイルをアップロード


          .o-proexhibit__productname
            .o-proexhibit__productname__formgroup
              = f.label '商品名', class: 'o-proexhibit__productname__title'
              %span.o-proexhibit__required 必須
              = f.text_field :name, class: "o-inputproductname", placeholder:'商品名（必須 40文字まで）'

            .o-proexhibit__productname__formgroup
              = f.label '商品の説明', class: 'o-proexhibit__productname__title'
              %span.o-proexhibit__required 必須
              = f.text_area :description, class: "o-inputproducttext", placeholder:'商品の説明（必須 1,000文字以内）（色、素材、重さ、定価、注意点など）例）2010年頃に1万円で購入したジャケットです。ライトグレーで傷はありません。あわせやすいのでおすすめです。'

          .o-proexhibit__explain
            = f.label '商品の詳細', class: 'o-proexhibit__explain__title'
            .o-proexhibit__explain__formbox
              .o-proexhibit__explain__fformgroup
                = f.label 'カテゴリー', class: 'o-proexhibit__productname__title'
                %span.o-proexhibit__required 必須
                .o-proexhibit__explain__from
                  -#親カテゴリーを呼び出す
                  -@category_parent_array = ["---"]
                  -Category.where(ancestry: nil).each do |parent|
                    -@category_parent_array << parent.name
                  = f.select :category,@category_parent_array, {}, {class: 'o-select', id: 'parent_category'}
                  %i.fa.fa-chevron-down.icon-bottom
              
              .o-proexhibit__explain__formgroup
                = f.label '商品の状態', class: 'o-proexhibit__productname__title'
                %span.o-proexhibit__required 必須
                .o-proexhibit__explain__from
                  %i.o-icon-bottom
                    =f.select :condition, Product.conditions.keys.to_a,{},{class:'o-select'}
                    %i.fa.fa-chevron-down.icon-bottom

          .o-proexhibit__explain
            = f.label '配送について', class: 'o-proexhibit__deivery__title'
            .o-proexhibit__explain__formbox
              .o-proexhibit__explain__formmgroup
                = f.label '配送料の負担', class: 'o-proexhibit__productname__title'
                %span.o-proexhibit__required 必須
                .o-proexhibit__deivery__from
                  =f.select :shipping_charge,  Product.shipping_charges.keys.to_a, {},{class:'o-select'}
                  %i.fa.fa-chevron-down.icon-bottom
              
              .o-proexhibit__deivery__formgroup
                = f.label '配送の方法', class: 'o-proexhibit__productname__title'
                %span.o-proexhibit__required 必須
                .o-proexhibit__deivery__from
                  =f.select :shipping_method, Product.shipping_methods.keys,{},{class:'o-select'}
                  %i.fa.fa-chevron-down.icon-bottom

              .o-proexhibit__deivery__formgroup
                = f.label '発送元の地域', class: 'o-proexhibit__productname__title'
                %span.o-proexhibit__required 必須
                .o-proexhibit__deivery__from
                  =f.select :shipping_area, Product.shipping_areas.keys,{},{class:'o-select'}
                  %i.fa.fa-chevron-down.icon-bottom

              .o-proexhibit__deivery__formgroup
                = f.label '発送までの日数', class: 'o-proexhibit__productname__title'
                %span.o-proexhibit__required 必須
                .o-proexhibit__deivery__from
                  =f.select :shipping_date, Product.shipping_dates.keys,{},{class:'o-select'}
                  %i.fa.fa-chevron-down.icon-bottom

          .o-proexhibit__price
            = f.label '販売価格(300~9,999,999)', class: 'o-proexhibit__price__title'
            %ul.o-proexhibit__price__formbox
              %li.o-proexhibit__price__formgroup
                %label.o-proexhibit__productnamee__title
                  価格
                  %span.o-proexhibit__required 必須
                %label.o-proexhibit__price__yen
                  ¥
                .o-proexhibit__price__from
                  = f.number_field :price, class: "o-priceselect", placeholder:'例）300'
              %li.o-fee
                .o-fee__left
                  販売手数料(10%)
                .o-fee-calculation
                  .o-fee__right
              %li.o-profit
                .o-profit__left
                  販売利益
                .o-profit-calculation
                  .o-profit__right
                  
          .o-proexhibit__btn
            .o-proexhibit__notes
              %p.o-proexhibit__note
                = link_to "禁止されている出品", root_path, class: "h-text-link"
                、
                = link_to "行為", root_path, class: "h-text-link"
                を必ずご確認ください。
              %p.o-proexhibit__note
                またブランド品でシリアルナンバー等がある場合はご記載ください。
                = link_to "偽ブランドの販売", root_path, class: "h-text-link"
                は犯罪であり処罰される可能性があります。
              %p.o-proexhibit__note
                また、出品をもちまして
                = link_to "加盟店規約", root_path, class: "h-text-link"
                に同意したことになります。
              = f.submit '変更する', class: 'o-proexhibit__linkred'
              = link_to root_path ,class: "o-proexhibit__return" do
                .o-proexhibit__linkgray
                  キャンセル
    
  = render "signup/signup-footer"

app/views/products/index.html.haml
= render "shared/header"
= render "products/product"
= render "shared/footer"

app/views/products/show.html.haml
-# Showページ

-# ヘッダ--------------------
= render "shared/header"
-# ------------------------

-# 商品詳細------------------
= render "products/details"
-# ------------------------

-# フッタ--------------------
= render "shared/footer"
-# ------------------------